### ISSUE TITLE
Password with special characters are not working

### ISSUE THREAD

**Issue by Viking-1** [leiweibau/Pi.Alert#106]
Especially the "$" symbol is not working. The password gets accepted but a login is not possible.

**Comment by leiweibau** [comment]
Yes, that is correct. Since I only enter the password as a simple parameter inside the terminal, I would have to escape characters like $/\ etc., but I don't do that at the moment. I could write the password in a string, but then " can't be used without further. Therefore the password is only provided as an alphanumeric string. I will add the hint to the documentation
