### ISSUE TITLE
Devices Reported as Offline 

### ISSUE THREAD

**Issue by phpavelic** [leiweibau/Pi.Alert#112]
Hi!
I'm currently facing the issue where most of my devices are getting reported as Offline even though they are online, and starting scans manually for each devices says they are online. What could be the issue here? 
Fresh install.

**Comment by phpavelic** [comment]
I've found out that when I'm using "SCAN_SUBNETS    = '--localnet'" everything works as expected, but switching to "SCAN_SUBNETS    = '192.168.1.0/24, 192.168.27.0/24'" makes it report some of the devices as offline.
local subnet is 192.168.1.0/24 and all devices I'm talking about are on that subnet.

I'm using MikroTik RB3011. All devices currently listed on pialert have static IPv4 assigned to them over DHCP server(MikroTik).

**Comment by phpavelic** [comment]
I've found out that when I'm using "SCAN_SUBNETS    = '--localnet'" everything works as expected, but switching to "SCAN_SUBNETS    = '192.168.1.0/24, 192.168.27.0/24'" makes it report some of the devices as offline.
local subnet is 192.168.1.0/24 and all devices I'm talking about are on that subnet.

I'm using MikroTik RB3011. All devices currently listed on pialert have static IPv4 assigned to them over DHCP server(MikroTik).

**Comment by leiweibau** [comment]
The entry `SCAN_SUBNETS = '192.168.1.0/24, 192.168.27.0/24'` was wrong and was deleted from the config by me a few days/weeks ago.

If you use only one subnet/VLAN, then please stick to the "--localnet" option. Otherwise, you need to specify/configure an interface for each subnet/VLAN for the scan to work.

**Comment by leiweibau** [comment]
The entry `SCAN_SUBNETS = '192.168.1.0/24, 192.168.27.0/24'` was wrong and was deleted from the config by me a few days/weeks ago.

If you use only one subnet/VLAN, then please stick to the "--localnet" option. Otherwise, you need to specify/configure an interface for each subnet/VLAN for the scan to work.

**Comment by phpavelic** [comment]
Alright then. Thank you very much.

**Comment by graphixillusion** [comment]
I'm having the same problem now. All my devices are offline but they are online. How to troubleshoot? It worked fine since yesterday. Today after a reboot i have only two devices online. I tried to restore an old backup and still nothing, it always sees 2 devices online

**Comment by leiweibau** [comment]
Thank you for the feedback. Please include at least the version of Pi.Alert used and possibly a scan log in future reports. Your hint is interesting in that I should possibly output additional information in the log.

**Comment by graphixillusion** [comment]
I'm using the last version. The log is clean, no error at all. I noticed that there was something wrong with the interface becouse i manually launched the command "arp-scan -l" and i saw that it was auto scanning the tailscale0 interface instead wlan0

**Comment by leiweibau** [comment]
I will include this behavior in the Help/FAQ.
