### ISSUE TITLE
Deleting devices - they keep coming back

### ISSUE THREAD

**Issue by dunxd** [leiweibau/Pi.Alert#120]
I installed today, alongside my existing Pihole implementation.  Very nice, thank you! I love monitoring!

So I've been trying to tidy things up, and remove all the (unknown) devices and phones that were set up to provide Random MAC addresses.

Frustratingly I found a few of these keep returning.  I realised that they were being picked up from my Pihole server in two places 

1. if the DHCP leases are still current, then from Settings > DHCP in the Currently active DHCP leases.
2. if the devices are listed in the Tools > Network table

Being able to search on MAC address in these two tables helped delete them.  However, I noticed that PiHole doesn't seem to do a good job of deleting recent devices from the Network table, and they keep returning to that table, and then back into Pi.Alert.

I wondered whether other people had come across this issue? Am I correct in thinking that the devices need to be removed from those two places in PiHole?

**Comment by leiweibau** [comment]
I also have this effect from time to time (preferably when I start one of my Raspberry Pi Zero). You can try to restart the computer on which Pi.Alert and pihole is installed. Otherwise, I would "archive" the devices that appear again and again, so that they disappear from the list for now. After a few days and possibly another reboot, I was then always able to delete the devices from pihole.

I'm sorry I can't give you a better answer here, as I haven't yet taken the time to analyze the problem in more detail. However, in my estimation it comes from pihole.

**Comment by dunxd** [comment]
Thanks - I wasn't aware of the archive feature.  I was going to ask if there was a way if ignoring devices - that seems to achieve the same.

I agree that the issue comes from pihole - the devices keep re-appearing there.  Probably pihole is populating the Network table from somewhere that caches devices for a while.

**Comment by dunxd** [comment]
It would be great if archived devices didn't show up in Unassigned devices on the Network page.

**Comment by leiweibau** [comment]
You're right, that makes sense. I'll see if I can implement that before the next update. I still have some things to document and rewrite on the Help/FAQ page to publish an update on 20.5., the "1st birthday" of this fork ;-)

**Comment by leiweibau** [comment]
I think the initial question has been answered, so I will close this Issue
