### ISSUE TITLE
Issue with Cleanup Script

### ISSUE THREAD

**Issue by upD8R** [leiweibau/Pi.Alert#122]
Hey,

I use your version for quite a while now and I do like the added features, keep going.
I just upgraded to your latest version and I have hoped my issue is solved, but it's not. Actually the cleanup script runs in an error with my DB, I guess this mismatch in the DB happened during one of the early upgrades.

```
pi@pihole ~> python3 ~/pialert/back/pialert.py cleanup

Pi.Alert  (2023-06-07)
---------------------------------------------------------
Current User: pi

Cleanup Database
    Timestamp: 2023-06-15 13:59:00

Cleanup Services_Events, up to the lastest 30 days...
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2602, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 103, in main
    res = cleanup_database()
  File "/home/pi/pialert/back/pialert.py", line 360, in cleanup_database
    sql.execute ("DELETE FROM Services_Events WHERE moneve_DateTime <= date('now', '-"+strdaystokeepOH+" day')")
sqlite3.OperationalError: no such table: Services_Events
```

Any idea, what I can do?

**Comment by leiweibau** [comment]
Hello,

I guess you didn't enable the "Web Service Monitoring" in the pialert.conf.

With the activation the database is extended. As long as this extension is not done, this error occurs because the script tries to clean tables which do not exist.

Activate the Web Service Monitoring for about 15min (SCAN_WEBSERVICES = True). Then the error should disappear. Maybe you like this feature and want to use it too. Otherwise you can deactivate it after 15min in the configuration file.

**Comment by upD8R** [comment]
Thanks, that solved it!
