### ISSUE TITLE
[Feature Request] List free/used IP addresses

### ISSUE THREAD

**Issue by alfwro13** [leiweibau/Pi.Alert#124]
First of all I just discovered this little gem of a project and it is exactly what I needed.  I use Home Assistant as a home automation platform and I have 50+ sensors, smart plugs and other smart devices on my home network. Most of them setup with a static IP address and it was getting hard to keep up with the changes. Pi.Alert no doubt will help a lot.
What I would love to see is the following options:
1. Mark device as a permanent (i.e. it won't be deleted by the maintenance scripts after x days of being offline)
2. Option to add manually devices (i.e. some of the sensors are in deep sleep and only wake up when something happens - for example a door sensor will wake up when door is opened/closed then it goes back to sleep)
3. Some kind of report that would list free/used IP addresses
4. IPv6 support

**Comment by leiweibau** [comment]
Hello,

To your listed points I can say the following:

1. no device is automatically deleted. The cleanup job only affects events and has nothing to do with the device list.
2. a manual addition of devices to the device list is not provided. The reason for this is that the MAC address is the primary index for a device. I do not plan to make this field editable. 
3. this could be thought about. However, I can't promise you that I will implement this feature in a timely manner.
4. the underlying arp-scan is only suitable for IPv4. In the meantime I experimented with ndp (IPv6). But I had to realize that this is not trivial in any way. A device has at least 3 IP addresses, which also change regularly or irregularly. It was not possible for me, also because of other effects, to get a reasonable implementation working. For this reason I stopped my experiments.

**Comment by alfwro13** [comment]
thanks anyways - great project, keep up the good work

**Comment by leiweibau** [comment]
I tried a little bit and found that the calculation is the smaller problem.

Do you have any idea where to place this IP list? Depending on the network used, a certain number of IPs can arise. Some use multiple network cards, which in turn result in additional lists. So it should be a place that can display 200, or even 2000 IPs. My configured network is 4000 IPs in size. There is no need to talk about sense and nonsense here.
