### ISSUE TITLE
jokob-sk/Pi.Alert 

### ISSUE THREAD

**Issue by alfwro13** [leiweibau/Pi.Alert#125]
Have you considered joining forces with jokob-sk (another fork of Pi.Alert: https://github.com/jokob-sk/Pi.Alert). I would appear that both of your project have some unique features and it would be great if they could be joined.
For example in the other project there is:
1. network maps generation: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/img/network.png
2. namp scan section where you can add notes for individual ports: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/img/device_nmap.png
3. config edited from GUI: https://github.com/jokob-sk/Pi.Alert/blob/main/docs/img/settings.png
 Thanks

**Comment by leiweibau** [comment]
Hello,

we both know each other's fork, have already supported each other on one issue or another, and I follow @jokob-sk's ideas with interest.

But since we have different approaches (Docker vs. bare metal), one or the other feature is either not implementable, or it makes no or little sense.

Regardless, the support I requested for a Docker port of my fork is also limited (it's not there).

Especially with his recent rebuild of the backend on @jokob-sk's fork, it's all the more difficult to find common ground.

For this reason, I would want to claim, there will probably be no unification of our forks and we can be happy to have an additional choice.
