### ISSUE TITLE
Enabling login generates 404s when using pi.alert instead of ip address.

### ISSUE THREAD

**Issue by Absoblogginlutely** [leiweibau/Pi.Alert#126]
New automated install of Pi.Alert (2023-06-15) on top of a Pihole installation with standard install of http://pi.alert.
After enabling the password, and logging in, the gui sends you to http://pi.alert/pialert/index.php which returns a 404.
I also found that using signout also directs you to the same page
Thankfully resetting the password to empty by  not providing a password to set_Password parameter  allows login's again, but the status page will show that logins are enabled.

Using the ip address to connect to the server instead of  pi.alert however will work successfully and you are able to login

**Comment by leiweibau** [comment]
Yes, you are right.

Explanation:
Pi.Alert is available at two URLs when you add Pi.Alert to Pi-Hole.
```
http://pi.alert/
http://$MAIN_IP/pialert/
```
I try to use relative URLs for Pi.Alert (e.g. also for login/logout). These URLs simply result from the folder structure. But since the whole frontend is now in the subfolder "pialert", this is of course also taken into cout. 
To fix this, I need to implement a function that detects how the frontend is called and then adjusts the links. Whether this affects all links, or only parts, I can not answer right now, because I do not use this configuration myself. But I am grateful for pull requests. Otherwise I will deal with that at a later time.

**Comment by leiweibau** [comment]
Find an error :)
https://github.com/leiweibau/Pi.Alert/blob/1eb5240ff30ca3fe15cdac8b62daaa8f637b89ae/front/devices.php#L15

**Comment by leiweibau** [comment]
Whether all the problems you described are now eliminated, I can not say at the moment. [#126](https://github.com/leiweibau/Pi.Alert/commit/550a311f65220358e793c0dde8a9d5926c23badb)
