### ISSUE TITLE
newest Update 

### ISSUE THREAD

**Issue by lastsamurai26** [leiweibau/Pi.Alert#132]
<img width="704" alt="Bildschirmfoto 2023-07-09 um 10 45 38" src="https://github.com/leiweibau/Pi.Alert/assets/3257844/fd7ca14b-d744-424e-a1d5-7c2c7c922f2c">

if you need more infos please ask

**Comment by leiweibau** [comment]
Thanks for reporting. 
Can you please check if you have the file/symlink "python3" in the directory "/bin"? Each of my test environments has this file.

Nevertheless, I have changed the path to to the probably more usual path. https://github.com/leiweibau/Pi.Alert/commit/b0f22df5f4ec307dc8991593d82e888de82d355c

**Comment by lastsamurai26** [comment]
in all other updates it had worked, but strangely now it does not. 
tomorrow I will check again if on the Pi (Debian 10) this path is present

**Comment by leiweibau** [comment]
> in all other updates it had worked, but strangely now it does not.

That is correct, because this change came with the last update. This is the preparation for the fact that in the future changes in the database should be performed by the updatescript and no longer during the runtime of the frontend or the backend. This is to prevent duplicate code and remove old code. 

However, the update should have gone through. The error occurred, in your case, when trying to stop Pi.Alert so that no database access happens during the database update.

**Comment by lastsamurai26** [comment]
ah ok, i had pi alert paused before like in the first message from the updater anyway so there should be no error. But good to know.

i will add the syslink myself if it not exists

**Comment by leiweibau** [comment]
i have changed the path to „/usr/bin/python3“ in the next version of pialert-cli. This path should exists.
