### ISSUE TITLE
[Feature Request] ping polling

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#134]
Very similar to the way web services work now, I'd like to suggest the ability to verify a device by pinging it.  Useful for devices that don't have an internal web page.

**Comment by leiweibau** [comment]
I understand your need.
My question now is: do you duplicate all the code for ICMP or do you build it into the web service monitoring? Both would have advantages and disadvantages.

I can't tell you yet if I want to do the effort for a simple ping, but I'll definitely leave the request open. Maybe something will come up.

**Comment by hspindel** [comment]
Okay, thank you.

**Comment by leiweibau** [comment]
I'm thinking a bit about doability right now (this is not a commitment that I'll implement the feature in a timely manner) and it begs the question: what kind of hosts do you actually want to ping?

**Comment by hspindel** [comment]
I want to ping local hosts that don't have web pages.  This will help with the devices behind WiFi extenders which can't work right with ARP scans.

**Comment by leiweibau** [comment]
> I want to ping local hosts that don't have web pages. This will help with the devices behind WiFi extenders which can't work right with ARP scans.

Ah ... okay. Have you already checked if this really works and the ping is not "answered" by the repeater?

**Comment by hspindel** [comment]
Yes, it will work as one hopes - the ping of the extender and the ping of the device behind the extender are at different IPs even though they appear to be the same MAC address.

**Comment by leiweibau** [comment]
I would love to accommodate you with this wish, but I really don't have an idea yet how to make it happen. 

My thoughts with pros and cons at the moment:
1. copy & paste of the "Web Service Monitoring" but with ping/ICMP function
   - Massive amount of duplicate code
   - With another protocol then again just copy & paste and triple the code?

2. extend the web service monitoring with a dedicated ping function
   - This requires a lot of exceptions to be added to ensure backwards compatibility
   - The table is unfortunately very specific at this point

3. as a device specific setting
   - Since in your case the spoofed MAC address (primary key in the database) is the problem, it could be that the wrong IP is then pinged. So it doesn't help you either.

So I am not any further. Do you have any other ideas?

**Comment by hspindel** [comment]
I can't comment on #1 and #2 because I don't know your code or the ramifications.

But regarding #3, the extender and the device behind it always respond correctly to a ping of the device's IP.  It's only the MAC address that gets spoofed.

**Comment by leiweibau** [comment]
I'll try to summarize it again for myself:

For example, you have a notebook with MAC 11:22:33:44:55:66 and IP 1.2.3.4. which is added to the device list in Pi.Alert like this.
If you are now in the range of the extender with the MAC aa:bb:cc:dd:er:ff a new device with the MAC aa:bb:cc:dd:er:ff and the IP 1.2.3.4. appears in Pi.Alert.

By using the Mac ignore list feature, you remove the MAC aa:bb:cc:dd:er:ff from the scan results. If you are now with the notebook in the normal WLAN, everything runs as it should. But if you are online via the extender, Pi.Alert reports that the Norbook is offline, because you ignore the MAC aa:bb:cc:dd:er:ff. Correct?

And if you don't ignore the MAC aa:bb:cc:dd:er:ff and you have multiple devices connected through the extender, you will constantly get messages that the device with the MAC aa:bb:cc:dd:er:ff has changed IP.

**Comment by hspindel** [comment]
I'm not sure that's quite right, and I don't think the MAC ignore feature quite helps now, although I have not tried it.

Configuration:
WiFiExtender @192.1.1.215, MAC 11.22.33.44
IoTDevice @192.1.1.237, MAC aa.bb.cc.dd

The extender has the unfortunate behavior of spoofing the MAC address of the IotDevice, so that the IoTDevice's MAC address appears to be 11.22.33.44 to piAlert (piAlert never sees aa.bb.cc.dd).

In some research I did, I found that many WiFi extenders exhibit this behavior.  The stated reason for doing so is to limit the number reported attached devices to the system router, because some routers have limits on the number of attached devices.  In the WiFi extender's settings, there is no way to disable this spoofing behavior.

If you ping the extender and the IoTDevice at the above IP addresses, they both respond correctly.

So if piAlert pinged 192.1.1.215 and 192.1.1237 for device presence, it would correctly determine that both are present.  Using the MAC address to locate these two devices is not working, because the MAC address is not reported accurately.

If you think the MAC ignore feature would help, I would be happy to try it.  The only viable choice would be to ignore the extender's MAC address, since piAlert never sees the IoTDevice's MAC address.

**Comment by alfwro13** [comment]
I have a similar problem but I don't think that ignoring MAC is the right way. I think it still should be discovered and option given to merge it with existing device.

**Comment by leiweibau** [comment]
> If you think the MAC ignore feature would help, I would be happy to try it.

"help" is a big word. 😉
It would reduce the effects a little, but would not eliminate the problem

> since piAlert never sees the IoTDevice's MAC address

In this case, a dedicated "ping" function would be the most reasonable option.

**Comment by leiweibau** [comment]
A detailed evaluation or time course would not be necessary?

**Comment by hspindel** [comment]
Not for me.  Just an up/down event.

**Comment by leiweibau** [comment]
Should the notification happen globally with the Pialert notification, or individually, as with Web Services?

**Comment by hspindel** [comment]
If I'm understanding right, I don't think it matters.  I'd just want up/down notifications.

I think what I would have to do is ignore the MAC address for the device and poll with IP instead.

**Comment by leiweibau** [comment]
Okay

> I think what I would have to do is ignore the MAC address for the device and poll with IP instead.

You can already disable all notifications for a Mac address. With the next release you will be able to create an IP/domain/hostname that will be pinged independently from the device list.
https://github.com/leiweibau/Pi.Alert/blob/main/docs/SCREENSHOTS.md#frontend---icmp-monitoring

**Comment by hspindel** [comment]
I look forward to trying it out!

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/ca55b2aa9f5e5059ef33fd837289532d9a2d8d87
