### ISSUE TITLE
[Feature Request] configure ARP-Scan period  / disable indefinitly

### ISSUE THREAD

**Issue by flwilk** [leiweibau/Pi.Alert#145]
I'd like to configure the period of ARP-Scans and if nessessary disable it indefenitly. Even after reboot!

**Comment by leiweibau** [comment]
So only the arpscan should be disabled, but not the reading of the pi-hole dhcp leases, the possible Fritzbox query and the web services?

**Comment by flwilk** [comment]
That ist the idea, because of the problems around arp-scan (blocking streams, locking up network)

**Comment by leiweibau** [comment]
At the moment the configuration is only possible via the configuration file. Whether there will be a button solution, I can not say. The pausing of Pi.Alert with automatic activation, however, is still available.

A GUI change of the scan interval will not be available for the time being, because the interval is set via a cronjob and this cannot be changed easily via a webfrontend.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/06c08aaa65a7998936d01d568a1ead4d95208cd5
