### ISSUE TITLE
[Bug] Unify method does not work

### ISSUE THREAD

**Issue by danielo515** [leiweibau/Pi.Alert#185]
Hello again.
I had setup some test configs in my instance, then I decided that I didn't wanted them because they were  failing, so I disabled them again. However, when I run a scan I see the same errors happening.
For example, I first enabled the pihole integration, tried a scan and it failed with a file not found (the DB was not there). No matter how many times I tried disabling it, I was getting the same error. Even after rebooting.

I then added the pihole file, just to check if that was the problem, and indeed  the issue was gone, now I'm getting the following error:

```
Scanning...
    arp-scan Method...
    Pi-hole Method...
    DHCP Leases Method...
    Fritzbox Method...
    Mikrotik Method...
    UniFi Method...
Traceback (most recent call last):
File "/opt/pialert/back/pialert.py", line 2755, in
    sys.exit(main())    
             ^^^^^^
File "/opt/pialert/back/pialert.py", line 108, in main
    res = scan_network()
         ^^^^^^^^^^^^^^
File "/opt/pialert/back/pialert.py", line 482, in scan_network
    read_unifi_clients()
File "/opt/pialert/back/pialert.py", line 758, in read_unifi_clients
    from pyunifi.controller import Controller
ModuleNotFoundError: No module named 'pyunifi'
```

It does not matter if I disable the unify method, this problem keeps happening.
How can I fix this? Do I need to remove the complet configuration?

**Comment by danielo515** [comment]
Commenting the relevant values makes it work again.
It seems you are only checking the existence of the values, and not the active flag

**Comment by leiweibau** [comment]
Since I don't have a Unifi system myself and the integration came into the project through a pull request, I can only help in a limited way right now. However, one thing stands out to me.

Does the error disappear if you make the following change in line 758 of the file "pialert/back/pialert.py"?

Change `from pyunifi.controller import Controller` to
`from unifi.controller import Controller`

**Comment by leiweibau** [comment]
After you have changed this, it is also necessary to remove the port specification from the config.

```
UNIFI_IP = '192.168.0.7'
```
The module already uses port 8443 internally

**Comment by leiweibau** [comment]
Upon further analysis, I have now found that there is a mismatch between the installed python unifi library and the function used in the script. I will install pyunifi instead of the python3 lib unifi with the next update. Unfortunately, however, I still can not test the functionality.

**Comment by leiweibau** [comment]
Update Released

**Comment by modem7** [comment]
Hey guys, 

Just putting in my 2 cents on this for how I've gotten this working. 

I've got a UDMP (dream machine pro), and this is how I've installed:

- Installed pyunifi via pip
- Edited ~/pialert/back/pialert.py to say `UDMP-unifiOS` instead of `v5` in https://github.com/leiweibau/Pi.Alert/blob/main/back/pialert.py#L752

**Comment by leiweibau** [comment]
Awesome. I add this as an option to the config file as well.

**Comment by leiweibau** [comment]
But it should be possible to suppress this warning. Such a log file should also somehow look a bit pretty 😉

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/37b6b1e7a051dec1668b86bea410f37ef4feb055

**Comment by modem7** [comment]
Can confirm that the new method works as expected, no issues found so far.

**Comment by leiweibau** [comment]
Thank you for your help
