### ISSUE TITLE
[Feature Request] Hypervisors

### ISSUE THREAD

**Issue by modem7** [leiweibau/Pi.Alert#189]
Heya, 

Some people have hypervisors on their network, and as such, things like virtual machines and containers can't be attached on the network page as there is no option to do so (as these items aren't connected to a switch/router/access point). 

My request is as follows:

- Under `Network`, allow the ability to create an entry for `Hypervisor` and `Container` (much like one would do for WLAN/Powerline). `Container` would cover things like Docker and Kubernetes with MACVLAN.
- Under `Connection Type`, allow for two additional labels such as "Virtual Machine" and "Container" (the latter would cover LXC, Docker and Kubernetes MACVLAN containers).

Allow the ability to attach the VM/Container to the Hypervisor (much like one would do with WLAN) under `Network`.

**Comment by modem7** [comment]
Whilst there is an argument to be made that containers are technically services, they do show up on the network diagram if one has set them up with MACVLAN so they have their own vMAC.

For example, these are some LXC containers I've created on Proxmox which show up on the network diagram as they have their own vNIC:
![image](https://github.com/leiweibau/Pi.Alert/assets/4349962/2f8a62c0-1f80-473d-bcf2-415bcf3e3413)

**Comment by leiweibau** [comment]
I also use different hypervisors in my network. I have handled it by assigning the VMs to the same port as the hypervisor. When doing this, the hosts/VMs are listed one below the other. 
Of course, I also understand the desire to display the VMs separately. I'll give that some thought.

**Comment by modem7** [comment]
I wasn't aware you could do that. 

Your method would be suitable (although I would recommend the VM/Container labels). 

It all depends on your viewpoint and obviously the cost/benefit on the rework.

**Comment by leiweibau** [comment]
Adding 1-2 labels and extending the code is a bit of work, but it's not too much. And there is no pressure, because this is a freetime project.

However, a rewrite will not happen so soon, because the presentation at the end looks simple, but the creation of the page is so convoluted that I have no motivation for the time being.

**Comment by modem7** [comment]
That makes sense! 

It makes sense to keep it on the backburner for now until such a time it becomes viable or someone with suitable python experience puts a PR in.

**Comment by leiweibau** [comment]
Adding labels should be possible with the next update in the next 1-2 weeks. If I have any questions, I will get back to you here.

Just to give a short explanation why this page "creeps me out" a bit 😉.

So that I don't have to make database queries again and again for the creation of the page and thus possibly block the scan, I load different tables in arrays. These are then used to generate the tabs and the content of the tabs. Thereby further arrays with arrays in them are created which are later read out again. In addition, there is the array for the different languages and arrays for exceptions such as the manual port configuration. 
To make it short: This page is a mountain of arrays whose content changes dynamically.

**Comment by modem7** [comment]
> To make it short: This page is a mountain of arrays whose content changes dynamically.

Jeez, I can absolutely see why. I shuddered at the explanation, and was very thankful I'm a backend engineer!

**Comment by leiweibau** [comment]
Here is a preview. Some tweaks are not done yet.

New Tab:
<img width="1248" alt="hyper_tab" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/513477f3-21a3-4378-9a1d-b76dc035c1c4">

New Device Type:
<img width="420" alt="hyper_type" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/49892d62-5347-4414-97a4-b08053d8b478">

Selection:
<img width="389" alt="hyper_target" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/085cfbc4-b4bd-42aa-a4e2-ae4793b88896">
<img width="407" alt="hyper_connect" src="https://github.com/leiweibau/Pi.Alert/assets/105860611/ef11da5a-2dc6-4f44-a310-427ebae7f620">

**Comment by modem7** [comment]
Oh that is absolutely perfect!

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/37b6b1e7a051dec1668b86bea410f37ef4feb055

**Comment by modem7** [comment]
Works perfectly, will close as complete. 

Thank you very much for the massively quick turnaround!
