### ISSUE TITLE
[Feature Request] Updated Network page

### ISSUE THREAD

**Issue by modem7** [leiweibau/Pi.Alert#190]
Currently on the `Network` page, when you connect a switch to a switch or a switch to a router, only one of them is updated.

E.g.
Connecting switch A to router A. On the `Network` page, only switch A has the connection.

So in the below diagrams:
Morgoth port 8 is connected to Gimli.
Gimli port 3 is connected to Morgoth.
But as we can see, only Gimli is updated.

![image](https://github.com/leiweibau/Pi.Alert/assets/4349962/6c12528f-4d74-4592-b91b-adb246a998d2)

![image](https://github.com/leiweibau/Pi.Alert/assets/4349962/6776b056-1c2e-41af-b179-b32cc6d76d84)

Unsure how best to do this, but it would probably need a rework of some sort. Maybe the ability to edit the ports on the `Network` page, as these devices are scannable devices.

This could be outside the scope of this project, but it's a QoL improvement.

**Comment by leiweibau** [comment]
Since there are quite complex configurations that cannot be mapped with a simple input mask for port number and destination, I have included a manual port configuration, which is, however, also somewhat more complex.

Docu
https://github.com/leiweibau/Pi.Alert/blob/main/docs/NETWORK_RELATIONSHIP.md

An older Issue
https://github.com/leiweibau/Pi.Alert/issues/91

**Comment by modem7** [comment]
Oh awesome! I didn't RTFM enough!

We'll consider this closed and I'll have a read through. 

Sincerely appreciated!
