### ISSUE TITLE
Installation waits for enter presses without prompting

### ISSUE THREAD

**Issue by hmeine** [leiweibau/Pi.Alert#226]
I have run the official install script on my Raspi 2 and waited a very long time after the first "Scanning linux images...".  After 10 to 15 minutes, I pressed enter just to see if the SSH connection was still alive and the installation continued. Of course, I pressed enter much faster the next times the "Scanning linux images..." progress bar disappeared (at least four times so far).

I do not know if this is intentional at all, but if it is, there should be a prompt like "Press [enter] to continue."

**Comment by leiweibau** [comment]
I can't remember at which point in the setup "Scanning linux images..." is output?

With Ubuntu Server I know that you have to press "Enter" every now and then during the installation. However, this only happens with Ubuntu Server and I have no idea why this happens and how to avoid it. But even there, I have not encountered the issue you mentioned. Do you perhaps have a screenshot?

**Comment by leiweibau** [comment]
Based on your descriptions, I have carried out another installation on an Ubuntu server.

It appears that you have also carried out the installation on such a server, because the message "Scanning linux images ..." appears here as well. Information on the operating system used is not unimportant and can save me a lot of time and nerves.

Now I don't know which version you are using, but in my test environment under 22.04.03 LTS it is no longer necessary to press the Enter key. However, I can also remember test installations where this was the case.

I will add this to the documentation at https://github.com/leiweibau/Pi.Alert/blob/main/docs/LINUX-DISTRIBUTIONS.md

**Comment by hmeine** [comment]
I have installed Pi.Alert on a Raspi running Raspbian. I can confirm now that the "Scanning linux images..." output also appeared in other `apt-get install` sessions, but I never had to press enter without a prompt before or after. (The system is rather old, has been updated many times, is now running Homebridge, Pi.hole, zigbee2mqtt, …) I believe, it was originally an official homebridge image that I put onto the SD card, and I am not sure about the relation to Ubuntu Server.
