### ISSUE TITLE
Migrating from Pucherot loses device name info

### ISSUE THREAD

**Issue by richtj999** [leiweibau/Pi.Alert#23]
Hi,

I am trying to move from the main branch to yours.  I have my devices named, owned, etc on Puucherot but upgrading to yours causes no devices to show up.  I also tried copying my pialert.db from his fork to yours but that doesnt work either.  Is there a way to migrate from one fork to another?

Thank you,
Rich

**Comment by leiweibau** [comment]
There is a patch script in the "install" folder. Copy your DB in the db folder, set the right permissions ("chmod 770") and the right user and group and then, run the patch script. Make a backup of your DB.

**Comment by gminadak** [comment]
I just moved form the main branch to yours to.
After i did what you said I come across the following error when i try to save any new information on details tab

![image](https://user-images.githubusercontent.com/45330594/184500444-5942baca-b2ba-4686-b33f-bd036b02b68b.png)
![image](https://user-images.githubusercontent.com/45330594/184500462-5e493072-0e8d-4095-8454-8c47b9617b5d.png)

**Comment by leiweibau** [comment]
If you just upgraded, then this is right. Open the Network-Page once. This page updates the table, then the error should be fixed. I will address this behavior in the FAQ.

**Comment by richtj999** [comment]
So what would the proper method be to swap from the original fork to your fork?  Do I need to do a database backup prior ?

**Comment by richtj999** [comment]
One other question - is there a way to run a single PiAlert for multiple Vlans - none of which are using PiHole as a DNS?  

Could I have a VM with multiple nics, on multiple Vlans and tell PiAlert to scan those vlans?

**Comment by leiweibau** [comment]
To the first question:
If it is important to transfer the database, then I recommend backing up the old database. Then reinstall Pi.Alert from my fork. After that copy the old database back to the directory with the same name and take care of the permissions (overwrite the existing db there). Now run the patch script and open the "Network" page in the Browser once.

Because of several changes I never checked the original update script and therefore removed it from my readme. 

If the database is not important. Just use the installation script. The database used there is completely updated.

**Comment by leiweibau** [comment]
According to the man page of arp-scan (the tool behind Pi.Alert) this is not so easy.

`arp-scan will search the system interface list for the lowest numbered, configured up interface.`

It might be possible to get arp-scan to use multiple NICs at the same time with a much more complex command. To experiment with this you can install arp-scan yourself. If you have found a solution and want to use it in Pi.Alert, I would be happy to help you with the implementation in your environment. Since I don't have such a configuration myself, I can't go into advance here.

**Comment by leiweibau** [comment]
Another possibility, not tested by me, would be to copy the pialert.py script in the back folder multiple times (e.g. pialert-vlan1.py, pyalert-vlan2.py, etc) and in each of these scripts set the interface to be used. Then extend the crontab accordingly. But what you have to keep in mind is that the database is not processed by the scans at the same time. As I said, I haven't tested it, wouldn't necessarily recommend it. But it could work, if I haven't forgotten anything.

**Comment by richtj999** [comment]
Sorry - Im not sure how to send this without it being an issue.  My eth adapters are ens160 & ens192.  

I wanted to check what you thought would be the best way to add the info into a pialert-vlan1.py script?  

My network is 192.168.80.0/24 for ens160
It is 192.168.99.0/24 for ens192  

What would you suggest i add into the 'new' file?

Also what would I do in terms of the extended crontab to make it scan the second pialert-vlan1.py?

Thank you very much!

**Comment by leiweibau** [comment]
Before you play with the scripts, first try with arp-scan alone, if everything works as you want it to.

Open a terminal and enter the appropriate commands:

sudo arp-scan --interface=ens160
sudo arp-scan --interface=ens192

While studying the arp-scan manual I saw that you can also use vlan tags. So you could also use a NIC that is in all vlans and test the following command

sudo arp-scan --vlan=number

But since I do not use such a setup, I can not test this myself.

**Comment by richtj999** [comment]
Leiweibau - thank you so much for helping me - this is great!  

In terminal I did these two commands (I checked your install log for the command):

sudo arp-scan --interface=ens160 -l | head -n -3 | tail +3
sudo arp-scan --interface=ens192 -l | head -n -3 | tail +3

Both commands generated an IP, Mac, and vendor on the two vlans.

Im looking at a newly created (by me) /home/rich/pialert/back/pialert-vlan80.py (assuming this is the right config file) but am not sure where to designate the arp-scan command to include the interface.  Do you have a suggestion on where I could try?

Thanks again!
Rich

**Comment by richtj999** [comment]
Thanks again for working with me on this - i really do appreciate it!  

I have tried the following edits to pialert.py

Attempt 1:
Line 501:
    arpscan_args = ['sudo', 'arp-scan', '--ignoredups', '--bandwidth=512k', '--retry=3', '--interface=ens160', '--localnet']
    arpscan_args = ['sudo', 'arp-scan', '--ignoredups', '--bandwidth=512k', '--retry=3', '--interface=ens192', '--localnet']

No error, no devices added to database

Attempt 2:
Line 501:
    arpscan_args = ['sudo', 'arp-scan', '--ignoredups', '--bandwidth=512k', '--retry=3', '--interface=ens160', '192.168.80.0/24']
    arpscan_args = ['sudo', 'arp-scan', '--ignoredups', '--bandwidth=512k', '--retry=3', '--interface=ens192', '192.168.90.0/24']

No error, no devices added to database

Attempt 3:  2nd pialert.py added - pialert2.py   (4th attempt was --localnet)  crontab -e changed
Line 501:
    arpscan_args = ['sudo', 'arp-scan', '--ignoredups', '--bandwidth=512k', '--retry=3', '--interface=ens192', '192.168.90.0/24']

No error, no devices added to database

Using:  sudo arp-scan --interface=ens192 --localnet   works fine (same with ens160)

I think its working but not adding to the database - is that possible?

**Comment by leiweibau** [comment]
only one command per script. try
`arpscan_args = ['sudo', 'arp-scan', '--ignoredups', '--retry=3', '--interface=ens160']`

There are many reasons why it does not work. Not without reason, there are also open issues at "pucherot". At a certain point, I can only guess what the reason could be in your case.

**Comment by jokob-sk** [comment]
Hey! I implemented support for multiple interfaces in this commit - it might work for your scenario as well - feel free to merge into your fork: https://github.com/jokob-sk/Pi.Alert/commit/929ea98fcef7d8b8af81181d97a8f9dff16665fe

Hope nothing else breaks. Open an issue on my fork if there is a problem and I'll have a look. Check the sample `pialert.conf` file on how to define multiple interfaces.
