### ISSUE TITLE
Bug: next scan counter vs cron job time set & different scan counters for arp scan / Internet IP scan

### ISSUE THREAD

**Issue by johnny-tknoska** [leiweibau/Pi.Alert#260]
Hello! 

Another small bug: In Scan Status @ Settings & Maintenance, the "next scan" counter always starts from 5 minutes to 0, no matter what the real cron timing is set to. For example, if you set the crontab to arp scan every 3 minutes instead of the default 5 minutes, the "next scan" counter should start from 3 to 0.

Also, a different "next scan"/scan counter should be created for Internet IP, as Internet IP scan job and arp scan job may differ in frequency, as it does by default (5 min for arp scan, 3 min for Internet IP scan).

Thanks again!

**Comment by leiweibau** [comment]
> the "next scan" counter always starts from 5 minutes to 0, no matter what the real cron timing is set to

Yes, that is correct. The coutdown timer is fixed to 5min, because I publish Pi.Alert with the 5min cronjob. The countdown does not check the cron setting. If this is changed, then this is a change to the code for which I am no longer responsible 😉 So it is not a bug. You are welcome to make a pull request to fix this. 👍

> Also, a different "next scan"/scan counter should be created for Internet IP, as Internet IP scan job and arp scan job may differ in frequency,

Of course I could also make a timer for the other things, but in my opinion this is unnecessary and also confusing in terms of quantity, as the associated database transactions are very fast. 
The background to the countdown was as follows:
Not everyone reads documentation consequently, it came to hints that changes were not applied e.g. on the detail page because the database is currently in read-only mode. This countdown was introduced to give the user an idea of when the next scan will start, i.e. when such a message might appear again. If 3-4 timers are now running here, this does not make it any better.

**Comment by johnny-tknoska** [comment]
Ok, thank you very much for your kind reply. I don't know too much coding so I don't feel comfortable trying to solve the countdown issue.
