### ISSUE TITLE
Automatic scans not working

### ISSUE THREAD

**Issue by leeandy1** [leiweibau/Pi.Alert#280]
I have installed the latest version of Pi.Alert on my Proxmox server and all seems to have gone well apart from its not performing automatic arp or web services scans. Running python3 ~/pialert/back/pialert.py initiates a scan and the devices update in the gui.

The following jobs are listed under the User Crontab

0 3 * * 1      python3 /opt/pialert/back/pialert.py update_vendors >/opt/pialert/log/pialert.vendors.log  2>&1
*/3 * * * *    python3 /opt/pialert/back/pialert.py internet_IP    >/opt/pialert/log/pialert.IP.log       2>&1
*/5 * * * *    python3 /opt/pialert/back/pialert.py 1              >/opt/pialert/log/pialert.1.log        2>&1
0 2 * * */4    python3 /opt/pialert/back/pialert.py cleanup        >/opt/pialert/log/pialert.cleanup.log  2>&1

Can you give me some pointers of what to do?

**Comment by leiweibau** [comment]
The things you describe raise several questions.

1. how did you install Pi.Alert? With the help of the Proxmox helper scripts (https://tteck.github.io/Proxmox/), or manually?

2. the path "~/pialert/back/pialert.py" points to the home directory of the executing user. However, since "/opt" is used in your cronjob, it cannot work.

3. in which directory is Pi.Alert installed (/opt, /root, /home/username)?

4. which path is stored in pialert.conf as the value for "PIALERT_PATH"?

5. which user has installed Pi.Alert? This user should then also be listed in the file "/etc/sudoers.d/pialert-backend"?

If in doubt, create a new container using the helper script. For these helper scripts, I have provided undocumented switches for the installation so that the special environment is taken into account.

**Comment by leeandy1** [comment]
Thank you for your reply.

I installed using the tteck script. I'll try a fresh container using the script and see where we go.

**Comment by leeandy1** [comment]
Ok so a fresh install seems to have done the trick and scans seem to be working as expected. Thank you.

I now cannot get the Speedtest Client to work. The client downloads successfully but reports file extraction failed. I have checked in the opt/pialert/back/speedtest folder and there is only a readme file. Any ideas?

**Comment by leiweibau** [comment]
This could be a permission problem.

However, to solve the problem the short way, you can also download the speed test (https://www.speedtest.net/apps/cli) yourself, unpack it and copy it to the directory "/opt/pialert/back/speedtest". This directory should then contain the readme, speedtest, speedtest.5 and speedtest.md.
To be on the safe side, run the speedtest once with "sudo ./speedtest" in this directory to agree to the license.

The file permissions must be set for www-data and the group permissions of the folder "speedtest" must be also "www-data" (drwxrwxr-x). The download button should then have disappeared in the frontend and the speedtest should be available.

**Comment by leeandy1** [comment]
Thank you. I used ./pialert-cli set_permissions and all is good now.

Thank you so much for your help. I'm new to linux.

**Comment by leiweibau** [comment]
And with just a little help, you solved a problem yourself 👍 I wish you continued fun and success in your work with Linux.
