### ISSUE TITLE
[Feature Request] Multiple WiFi Access Points

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#297]
Hi,

When you add devices to switches you can add it to multiple ports like using comma's like "1,2,3,4". I use this a lot when setting up LACP so it's good and useful.

But when adding devices which are portable and might roam between different access points you can only add them to one access point.

Is there a way you can add WiFi devices to be assigned to more than 1 WiFi Access Point in case it moves?

I realise there might not be a way for it to detect which AP it's connected to so just have it light up on all saying it's online still. Unless you can think of a way to identify which AP it's connect to and just have it appear on that one?

Thanks for your consideration.

**Comment by leiweibau** [comment]
What do you think about this?

https://github.com/leiweibau/Pi.Alert/assets/105860611/e4b5be4b-8d89-485f-9ee4-efa28f466cb9

**Comment by leiweibau** [comment]
> Yeah that looks great but I'm just wondering why you can't just

Because the functions that work in the background can't handle it. This requires new, more complex functions. The overview was originally intended to be composed of the device list like a "tree diagram". The configurations that are now possible go far beyond this. 

The drop-down list adapts itself depending on the type, and the types could be changed so that the correct or a sensible selection is displayed.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/91d0f5770f2498e084d0167b202029f841974e4c
