### ISSUE TITLE
[Feature Request] Multiple switches and additional fields

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#298]
Hi,

I have switches that connected to more than one switch.

Is it possible to be able to have more than one uplink target?

Also, can you add a connection type "Fibre"

Lastly, can you add connection speeds for Ethernet? Possibilities I would suggest but also leave it editable for other possibilities.
10 Mbps
100 Mbps
1000 Mbps
10000 Mbps
20000 Mbps
25000 Mbps
40000 Mbps

Thanks.

**Comment by leiweibau** [comment]
> I have switches that connected to more than one switch.
Is it possible to be able to have more than one uplink target?


In the past, I have made a few improvements to the manual port configuration in terms of usability. This should make it possible to configure this scenario.

**Comment by leiweibau** [comment]
No, I am referring to https://github.com/leiweibau/Pi.Alert/blob/main/docs/NETWORK_RELATIONSHIP.md#lagg-hostserver-to-one-switch (Case 2)

Today I was thinking about the challenges involved in rewriting the network overview.

I only use one field for the input:
All previous configurations would become invalid. Well, you could perhaps live with that. My approach here would be the following syntax: 1. device ID:port, 2. device ID:port, etc.
However, a distinction must be made here if no port specification makes sense (WLAN, hypervisor, powerline). This is certainly feasible somehow, but it means a huge amount of work because the entire logic of the previous page creation changes.

I stick with 2 input fields and extend the target field and the property that the port field has:
Previous configurations could be retained. But, no. That doesn't work. Example:

```
Switch A is connected with LAGG (2) to Switch B and with a connection to Switch C.

Target field: 2,3
Port field: 15,16,1

I can now guess which ports belong to which switch.
```

Unfortunately, this means for me at the moment (unless I'm missing something) that WITHOUT a rewrite at this point, I unfortunately cannot fulfill your request (this applies to your other feature request). Perhaps I can still manage a small hack or two to satisfy you a little more.

The thing is, the manual port configuration does exactly what I have in mind with the 1 field solution.

Another approach would be to remove the port assignment completely from the device details and make the network overview basically independent of it. All potential devices (switches, routers, etc) are in a list, you define the ports as you do now and then click together the devices for the individual ports. This also means rewriting the network overview, but I think it simplifies the compilation of the data. In this case, it would even be possible to run both overviews in parallel and thus facilitate migration.

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/530948a7e9b2b0d78d3168e44ec55f68d0417b0c
