### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by celesduran** [leiweibau/Pi.Alert#30]
Would it be possible for you to add notifications through Telegram?

**Comment by leiweibau** [comment]
The support of "Telegram" is one thing, but the quite complex configuration of the interface to actually communicate with the Telegram network is a completely different problem. Since I am not a Telegram user myself, an implementation would go beyond just providing support, since I would have to register and then configure the other tools to connect to the Telegram network before I can even start extending Pi.Alert. Also, I am not willing to provide support afterwards for the quite complex configuration in case something doesn't work.

I hope you understand that. This Pi.Alert fork is just a hobby of mine. With such complex interfaces, I don't want to turn the hobby into work.

**Comment by leiweibau** [comment]
I had a little look at "shoutrrr" and found that this package also exists without Docker. Currently I got it executable. Maybe I'll add some support after all.

**Comment by celesduran** [comment]
Thanks a lot. I'll be waiting for it

**Comment by leiweibau** [comment]
Take a look at https://github.com/leiweibau/Pi.Alert/commit/d83192a4c7a8065b1da35eb607118f7bd206449a or https://github.com/leiweibau/Pi.Alert/commit/19ffafb73ef2431b07efcbd5fd5e7e2115f54a01
