### ISSUE TITLE
monitor multiple network range with 1 pi.alert

### ISSUE THREAD

**Issue by javifly** [leiweibau/Pi.Alert#306]
hello,

I have the pi.alert on the network 172.16.0.1 working perfectly and it monitors the whole range 172.16.0.1 to 172.16.0.255, how can I monitor other network ranges as well?

I mean my firewall interconnects 3 networks:
172.16.0.x
172.16.1.x
172.18.1.x

From the 3 networks all the computers can be seen and respond to ping. I would like to be able to monitor the 3 networks from only 1 pi.alert. Is it possible, or do I have to put a pi.alert in each network independently?

Translated with DeepL.com (free version)

**Comment by leiweibau** [comment]
Duplicate

Look at https://github.com/leiweibau/Pi.Alert/issues/299

**Comment by javifly** [comment]
I understand that the pi.alert virtual machine must have 3 network cards to be able to scan 3 different network segments?

Can't a single network card scan 3 different network ranges?

**Comment by leiweibau** [comment]
You can also configure virtual network interfaces. It is important that there is an interface for each subnet.

> Can't a single network card scan 3 different network ranges?

I'll ask the question the other way around. You have surely created the 3 subnets so that you have separated the devices of the individual networks from each other in order to possibly increase your security. Why should a single host simply be able to ignore these security boundaries?

Of course, you can also monitor a few individual devices with ICMP monitoring if it is ensured that these devices always receive the same IP. However, in order to recognize whether a new device is in the network, Pi.Alert must have the broadcast of the subnet available and this is only the case if there is a direct connection to the network. You could also do a nmap scan on the subnet, but at best you will only get the IPs, but not the MAC address, which is needed to uniquely identify the hosts

**Comment by javifly** [comment]
Exactly! You are right!

I have the VPNs separated for better security and for that it would be better what you said.

But on top of the VPNs there is a firewall and 4 different internet connections. In other words, my scheme is like this:

<img width="314" alt="image" src="https://github.com/leiweibau/Pi.Alert/assets/38109926/116e0687-46e9-4fb0-a2ba-9fb5e6d31cbd">


I can easily put equipment on NET 1, NET 2, NET 3 but I can't do it on the other networks:

172.17.0.x
172.17.1.x
172.17.2.x

and even less on the 

172.18.1.X

They are networks that have 2 or 3 ips assigned to them and all of them are static, that is why I would be interested in monitoring that no one new is added to those networks and it has to be from one of the lower networks.

So far I do it with a nmap script and icmp to the range of these IPs, I do not locate the MAC but if I see a rare IP in them, it alerts me by mail.

I wanted to get rid of my script and monitor with a more complete and powerful graphical tool like this one.

Translated with DeepL.com (free version)

**Comment by leiweibau** [comment]
I haven't answered anything yet because I don't know what to say.

I don't see any way in which you could "monitor" the 172.17.0.x, 172.17.1.x, 172.17.2.x, 172.18.1.x networks, i.e. check whether new hosts have been added. I have not yet implemented a nmap scan (as you are currently doing), which in principle pings through all IPs of a subnet, because I still have no idea how/where to save the result. 

For the 3 other networks you can now either configure a host that has access to all networks, or create 3 independent instances, which then results in 3 different management interfaces (WebGUI). However, this would not matter for the notification.

**Comment by javifly** [comment]
ok, thanks for the answer. I just wanted to know that you had read me. I think your answer is correct, thank you. For now I will continue using a script I have to ping IP by IP to those networks 172.17.x.x and 172.18.x.x and I will use pi.Alert for the 172.16.x.x as well.

I want to use pi.alert and follow the project, and see the updates as they are released. If finally something like this is released I will remove my scripts and leave only pi.alert. But for the moment I have to use both solutions.

Thanks a lot

**Comment by jokob-sk** [comment]
With NMAP scans the issue seems to be that you don't always get the MAC address, which then makes it difficult to use as the only way how to detect devices. I went thru a similar scenario previously when developing an NMAP scanner plugin: https://github.com/jokob-sk/NetAlertX/issues/645 

So even with NMAP implemented, there are limitations on how originally PiAlert was setup - with the MAC address being the primary ID. My conclusion was, that NMAP has to be complemented with another scan method for discovery (and then NMAP is used of online/offline detection) or you have proxies to detect devices individually on these networks (this then defeats a bit the purpose of having one central application). Just my thoughts on this topic.

**Comment by javifly** [comment]
It seems that it was thought that the MAC would be the unique key that identifies the device, and because in those networks you cannot identify the mac you could not register the device.

There are always options, program something like:
- When the MAC is not detected save the device by typing in the MAC field its ip e.g. 192.168.1.90. 
- When the MAC is not detected save the device by typing in the MAC field its ip a fictitious one: 00:00:00:00:00:00:00:01 and so on with the following 00:00:00:00:00:00:00:02, 00:00:00:00:00:03 etc...

there can be many options... thinking that there may be situations where the mac is not detected but if you can see if there is a computer on an IP or not and detect the intrusion.

**Comment by jokob-sk** [comment]
Not bad ideas, but:

- When the MAC is not detected save the device by typing in the MAC field its ip e.g. 192.168.1.90.

This would break other functionality, such as identifying randomized mac addresses, vendor detection.

- When the MAC is not detected save the device by typing in the MAC field its ip a fictitious one: 00:00:00:00:01 and so on with the following 00:00:00:00:02, 00:00:00:00:03 etc...

This would break other functionality, such as identifying randomized mac addresses, vendor detection, and if the device is detected elsewhere, duplicate detections of the same device. 

Happy to entertain other options, just saying I spent a good amount of time thinking about this. Not sure if there is an elegant solution or a more thorough application rewrite is necessary, which requires a lot of effort.

**Comment by javifly** [comment]
Thank you, I hope you find a simple solution.

**Comment by leiweibau** [comment]
I am closing this issue because no solution to the question can be offered here at the moment
