### ISSUE TITLE
[Feature Request] Better docker support

### ISSUE THREAD

**Issue by NossieUK** [leiweibau/Pi.Alert#315]
I have 50 + containers running on my poor little pi 8GB.... pi alert keeps detecting the containeras as new devices - it would be nice if it atleast understood what was going on.

![image](https://github.com/leiweibau/Pi.Alert/assets/93691973/2eb125dc-064d-4e3b-913f-2c3799b96980)

Sadly without that - detection is a bit of a mess.

Thank you - Ian.

**Comment by leiweibau** [comment]
Since Docker containers are always given a new MAC address, they are also recognized as a new device. This is precisely the task of Pi.Alert. Do the recognized MAC addresses have a recognizable scheme? So are there parts that are always or often the same? Then you could enter this in the MAC Ignore list. This should significantly reduce the number of messages.

MAC_IGNORE_LIST = ['MAC-Address 1', 'MAC-Address 2']
This MAC address(es) (save with small letters) will be filtered out from the scan results. It is also possible to specify only the beginning of a MAC address. All addresses with the same prefix will also be filtered out.
