### ISSUE TITLE
[Feature Request] Markierung von ausgeschlossenen Geräten

### ISSUE THREAD

**Issue by fobi87** [leiweibau/Pi.Alert#355]
Hallo.

Ist es möglich die Geräte in der Status-Spalte zu markieren die von einem Scan ausgeschlossen sind (Scan Zyklus = 0)?

Desweiteren wäre es von Vorteil wenn man den Scan Zyklus beliebig einstellen könnte.

Danke Dir.

Liebe Grüße
fobi87

**Comment by leiweibau** [comment]
Hallo

> Ist es möglich die Geräte in der Status-Spalte zu markieren die von einem Scan ausgeschlossen sind (Scan Zyklus = 0)?

Da muss ich mir mal Gedanken drüber machen. Da ist komplexer als er erstmal klingt. Zum einen muss der AJAX-Call diese Daten liefern, was ich gerade garnicht weiß. Zum Andern muss da in Datatables/JS entsprechend gefiltert werden. Ob und wann ich dies Implementiere, kann ich dir nicht sagen. Ich freue mich aber über Push-Requests.

> Desweiteren wäre es von Vorteil wenn man den Scan Zyklus beliebig einstellen könnte.

Um den Vorteil zu verstehen, müsste ich wissen, was du damit meinst. Scannen oder nicht scannen. Was möchtest du hier "beliebig" einstellen?
Zur Erklärung: 
Beim ursprünglichen Projekt gab es noch einen weiteren Scan, der alle 15min startete. Das war im Prinzip ein zusätzlicher Zyklus. Im meinem Fork habe ich mich davon getrennt, weil diese, zum Teil doppelt laufenden Scans durchaus Auswirkungen auf die Netzwerk-Performance von Netzwerkteilnehmern hatten (gerade IoT Geräte). Es bringt in meinen Augen nichts, wenn man das Netzwerk mit Scans zumüllt um alles sofort zu erkennen, man das Netzwerk dann aber nicht mehr nutzen kann.

<hr>

> Is it possible to mark the devices in the status column that are excluded from a scan (scan cycle = 0)?

I'll have to think about that. It's more complex than it sounds at first. On the one hand, the AJAX call has to provide this data, which I don't know at the moment. On the other hand, it has to be filtered accordingly in Datatables/JS. I can't tell you if and when I will implement this. But I am happy to receive push requests

> Furthermore, it would be an advantage if you could set the scan cycle as desired.

To understand the advantage, I would need to know what you mean by this. To scan or not to scan. What do you want to set "as desired" here?
To explain: 
In the original project, there was another scan that started every 15min. This was basically an additional cycle. In my fork, I got rid of it because these scans, some of which ran twice, had an impact on the network performance of network participants (especially IoT devices). In my opinion, there is no point in filling the network with scans to detect everything immediately, but then you can no longer use the network.

**Comment by lastsamurai26** [comment]
Ich bin der Meinung alle 5 Minuten mit 6 Versuchen sollte reichen, ich habe die original Version mal bei uns in der Firma eingesetzt gehabt. Wir haben hier ca. 1000 Server und Clients, AP inbegriffen und durch die Scans von Pialert wurde das Netzwerk so dermaßen lahmgelegt das wir nicht arbeiten konnten wenn er seinen Scan gemacht hat. 

Mit dem Fork merken wir es nicht mal das er scannt aber wir sehen es aber trotzdem auf der WebGui. Und des weiteren mit der neuen Funktion der Satelliten haben wir die Möglichkeit das ganze Netzwerk übergreifend zumachen, bedeutet das wir mehr als nur 1 Netz beobachten können 

------


I think every 5 minutes with 6 attempts should be enough, I used the original version in our company. We have about 1000 servers and clients here, including AP, and the network was so paralysed by Pialert's scans that we couldn't work when he did his scan. 

With the fork we don't even notice that he is scanning but we can still see it on the WebGui. And furthermore with the new function of the satellites we have the possibility to make the whole network comprehensive, which means that we can observe more than just 1 network.

**Comment by leiweibau** [comment]
@lastsamurai26
Wow. Da beeindruckt mich. Dankeschön für das entgegengebrachte Vertrauen.

<hr>

Wow. That impresses me. Thank you for the trust you have placed in me.

**Comment by leiweibau** [comment]
Wegen folgender Gründe geschlossen.
1. Der Aufwand zur Implementierung ist größer als der Nutzen. Für Pull Requests bin ich offen
2. Fehlendes Feedback auf Rückfragen.

<hr>

Closed for the following reasons.
1. the implementation effort is greater than the benefit. I am open to pull requests
2. lack of feedback on questions
