### ISSUE TITLE
[Bug] cannot view some devices

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#358]
Hello.
I have this issue where some of my devices cannot be seen on their respective details pages, there is a "Quering device info..." message at the top and no fields get populated in the "Details" page. I also have the beachball cursor over the webgui. (sidenote : I think it should be Querying, not quering)

All the devices that exhibit this issue are Mikrotik SwOS devices (switches), and they have a dash in their hostnames. Also, their hostnames are not correct in the Devices list page, I see weird numbers instead. These numbers do not appear in the Details page.

<img width="580" alt="Screen Shot 2024-08-19 at 9 30 48 PM" src="https://github.com/user-attachments/assets/104740c5-11b2-4f3b-a9cb-3718fde2be0e">
<img width="548" alt="Screen Shot 2024-08-19 at 9 36 20 PM" src="https://github.com/user-attachments/assets/14e12b4c-a62e-4907-b565-8bdf07153711">
<img width="310" alt="Screen Shot 2024-08-19 at 9 38 09 PM" src="https://github.com/user-attachments/assets/55f4dca6-110b-4289-92c2-dde3b07c02ae">

### Environment

Debian GNU/Linux 12 (bookworm), Raspberry Pi 3

**Comment by leiweibau** [comment]
Unfortunately, I can't help much at this point, as I have to rely on pull requests for the "microtik import". I do not own these devices myself. The only way I can currently see to possibly gain some insight into the problem would be to take a look at your database. Because it may not necessarily have to end up on GitHub, I offer to send it to leiweibau@gmail.com if you like. However, I can't promise you whether I'll be able to find and fix the problem.

**Comment by stanelie** [comment]
Hello.

I sent you the database. I hope you can find the problem.

Thanks!

**Comment by leiweibau** [comment]
The database has arrived. I will take a look at it and test it.

**Comment by leiweibau** [comment]
I have now found some time to look at this problem.

In your case, for some reason unknown to me, numbers have been entered as the host name. The database has no problem with this, but the JavaScript, which loads the data into the fields when the page is loaded, does. My current fix is in the backend, which checks whether the hostname is a number or a floating point number. If this is the case, the addition “(Invalid Hostname)” is appended, which, funnily enough, makes it a valid hostname again.

I haven't found a fix in the frontend yet, but I'll have another look later.

> I can now see and edit this device in pi.alert. However, the hostname field defaults to (unknown) instead of the published hostname after the device is first discovered.

I don't really understand that. The attempt to determine a host name is actually only made for the host name “(unknown)”. I have no explanation here as to why a changed host name is set to “(unknown)” again.

**Comment by stanelie** [comment]
Shouldn't the hostname field be a string field and never be a number or
float, regardless of what the content is?

**Comment by leiweibau** [comment]
That is correct. So far, nobody has had the problem that only numbers have been entered in the hostname field. It is also saved as a string in the database. When the data is read out, it is written to an array and converted into JSON, which is then transferred to the frontend. When reading out or converting to JSON, the host name became an INT or FLOAT if no letter was present because it was a mixed var. With the fix, it is now already determined when reading from the database that it is a string and not a mixed var.

**Comment by stanelie** [comment]
Ah! I understand. Thanks!

**Comment by leiweibau** [comment]
Update released with https://github.com/leiweibau/Pi.Alert/commit/cf37c8f9d7241b3ec4779a98ab9bda0a57d8dbcb
