### ISSUE TITLE
[Feature Request] Use filters in the Presence view

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#359]
Hello.

I would like to be able to use the filters created under the Devices view in the Presence view.

Thanks!

**Comment by leiweibau** [comment]
I've already given it a thought or two, but would probably limit myself to supporting the satellites for the time being. However, I haven't started any concrete work here yet.

**Comment by leiweibau** [comment]
To illustrate the current display of the sidebar

<img width="221" alt="navbar" src="https://github.com/user-attachments/assets/4c77ea59-712b-4861-8b15-375bbd7b0dba">

**Comment by leiweibau** [comment]
Since this and the feature request https://github.com/leiweibau/Pi.Alert/issues/363 influence each other, I will only follow one of the two ideas further (part of the filtering has already been achieved by splitting into “local” and satellites).
Personally, I like the other feature request more, as this idea does not make the structure more complex, but offers the possibility of making the presentation simpler and clearer.
