### ISSUE TITLE
Missing notifications after template modification

### ISSUE THREAD

**Issue by stanelie** [leiweibau/Pi.Alert#367]
I've noticed that there are missing notifications in the notification view of the web gui. I did indeed receive a notification to my NTFY service, the little badge counter in the top right corner of the web ui does indeed show a count for that notification, but the notification is not in the notification view : 
![image](https://github.com/user-attachments/assets/75acfaa2-27b2-4294-8ffc-6fc38c44f186)

This is a recurrent bug for me.

### Environment

raspbian bookworm, raspberry pi 3

**Comment by leiweibau** [comment]
Can you please run the command “ls -al” in the “pialert/front/reports/” directory?
Only reports that I have “formatted” are displayed. Actually, all report types should be included.

**Comment by stanelie** [comment]
Hum... I customized the report_template.txt file so that it displays correctly on my smartwatch with less scrolling, could that be causing this issue?

Here is the content of my report_template.txt file : 

```
<SECTION_NEW_DEVICES>
<TABLE_NEW_DEVICES>
</SECTION_NEW_DEVICES>
Report Date: <REPORT_DATE>
Server:      <SERVER_NAME>

<SECTION_INTERNET>
Internet
----------------------
<TABLE_INTERNET>
</SECTION_INTERNET>
<SECTION_DEVICES_DOWN>
Devices Down
----------------------
<TABLE_DEVICES_DOWN>
</SECTION_DEVICES_DOWN>
<SECTION_EVENTS>
Events
----------------------
<TABLE_EVENTS>
</SECTION_EVENTS>
```

**Comment by stanelie** [comment]
I have 2 report files in the pialert/front/reports/ directory, and these two reports are the ones not showing up in the notifications view of the web interface.

**Comment by leiweibau** [comment]
You can say here: “Yes, you broke it” 😉

To explain:
The reports have a fixed naming scheme. This naming scheme is created using the template TXT files, as I know exactly where which text is located in this template. If you now edit this template, it may be that I can no longer find the text I expect in a certain line. The part then collapses.

Finally, the report type is missing for both files, which is why the reports are not displayed. However, as the counter at the top right only counts “.txt” files in the directory, it shows you the number of reports.

**Comment by stanelie** [comment]
Ah, thanks for this explanation.
