### ISSUE TITLE
Service fails to start due to Apache2 / Lighttpd conflict

### ISSUE THREAD

**Issue by dustingrady** [leiweibau/Pi.Alert#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

The GUI seems to be unreachable, and when looking at the service list I see that Apache2 has failed to start due to a conflict on port 80, as it is already "in use" by Lighttpd.

Stopping Lighttpd allows Apache2 to start, but then Lighttpd cannot. Things had worked fine for quite some time and this recently began happening. Not sure if this is a regression or a one off.

### Environment

**OS:** Debian 12
**Environment:** Installed on a Proxmox VM directly (no containerization)
**Arch:** x86_64

**Comment by leiweibau** [comment]
Hello,

> <title>
The idea was to use a meaningful headline for this placeholder. Like „ Service fails to start due to Apache2 / Lighttpd conflict“ 😉

You've actually already done half of the troubleshooting yourself, which I think is great. 
Since there are certainly reasons why you have also installed the apache web server, I cannot advise you to uninstall it. The simplest option would be to change the port for Pi.Alert.

https://www.lightnetics.com/topic/16731/how-do-i-change-the-default-lighttpd-web-server-port

**Comment by dustingrady** [comment]
Doh! Early morning mistake. Thank you, I'll give this a try.

**Comment by dustingrady** [comment]
Was able to change port to resolve systemd error.
