### ISSUE TITLE
Scan on 3 phisical interfaces

### ISSUE THREAD

**Issue by intheshell** [leiweibau/Pi.Alert#40]
Hello man how are you?,

I m very interested in pi.alert, currently I have it installed in a container with a physical interface in proxmox and it works great, but I would like to add 3 more interfaces, will it be possible to scan that entirety?

According to the documentation, you would have to make changes to back\pialert.py by commenting and uncommenting some lines. I have tried to do it with a single additional interface and when making the modification in the Back I have not been able to make it work. which may be the issue?

Regards

**Comment by leiweibau** [comment]
Some time ago I did some tests with interface binding, which is the "basis" for your idea. At that time I also encountered error messages. I haven't checked what the problem is yet, because it has a low priority for me. Since you are using the Docker version, you actually have everything you need, since @jokob-sk has already implemented this (as far as I know).

**Comment by jokob-sk** [comment]
@intheshell yep, it should work, follow the instructions in the config file: https://github.com/jokob-sk/Pi.Alert/blob/f7fbf9488a9605ded4821149d50af04e5858a6d8/config/pialert.conf#L111
