### ISSUE TITLE
Help / FAQ section removed in latest release

### ISSUE THREAD

**Issue by johnny-tknoska** [leiweibau/Pi.Alert#405]
OMG! You removed the Help/FAQ section in the new release. I know many people didn't read it and asked you many times for information that was clearly explained there, but removing it doesn't help people who see it...

There was a lot of useful information there that I used several times (my memory is short).

Will you not restore this section? Or are you just taking some time to clean it up and put it back up?

I'm aware that keeping this section updated and seeing that many people don't use it is heartbreaking, but an intermediate option could be to just keep it as it was and not update it anymore or just remove disabled items.

Thanks a lot for your great work!

**Comment by leiweibau** [comment]
Thank you for your kind words.
Yes, as announced in an issue last week and in the release notes, I have removed that part. Despite the use of generative AI, the maintenance was quite complex and time-consuming. Most of the queries were about the time on the right, even though the reference to this was the first entry in the help. Since configuration is now possible via pialert.conf, this question is hopefully no longer necessary. That reminds me, I haven't updated the documentation for pialert.conf yet. 🤦‍♂️ 
Other points such as the documentation for pialert.conf or pialert-cli still exist in the "docs" folder, but only in English. Other things that were in the Help/FAQ section can already be found there, or will appear there in one form or another in the near future. I am planning at least a small Troubleshoot Guide (there is already a document in the folder) and also a small revision of the "Guide for the first start".

**Comment by johnny-tknoska** [comment]
Ok! Thanks for your answer. Maybe a link in the app to https://github.com/leiweibau/Pi.Alert/tree/main/docs is enough....no problem only in english; I think today it doesn't make sense to translate as there are many online tools to help anyone with poor english knowledge.
