### ISSUE TITLE
[FAQ] Error on writing DB after restoring a backup

### ISSUE THREAD

**Issue by sylar6725** [leiweibau/Pi.Alert#43]
Hi.
After a backup restoration, the owner of the file pialert.db change to "www-data"
![image](https://user-images.githubusercontent.com/71662117/206340348-e070a0fa-68b7-4fde-a8e0-912e68a57bba.png)
that cause an error when writing db 
![image](https://user-images.githubusercontent.com/71662117/206340753-6fa43899-56b6-4d73-9fe3-9b298d0ebe79.png)
I need to do 
`sudo chown USER pialert.db`

Best regards

**Comment by leiweibau** [comment]
I will check that. Thank you for reporting.

**Comment by leiweibau** [comment]
Feedback on your finding:

The problem is that a restore is performed via the website under the user "www-data". There are several ways to handle the problem, but depending on the environment, either one or the other will work:

Solution 1:
The user under which Pi.Alert is installed becomes a member of the "www-data" group.

Solution 2:
The backend can set the permission before each scan. For this, the user under which Pi.Alert is installed must be set up in the sudoer.

Solution 3:
"unzip" could set the permission, but then "www-data" must be set up at the sudoer!!!!!! Better not.

Solution 4:
Refrain from restoring backups via the website.

Solution 5:
Leave everything as it is and document the problem in the FAQ.

**Comment by leiweibau** [comment]
If you prefer solution 2: https://github.com/leiweibau/Pi.Alert/commit/c5c7848cc4b6f5b0c8ce3a3660d544b7aa0f8be5 should work

**Comment by leiweibau** [comment]
If you prefer solution 5: https://github.com/leiweibau/Pi.Alert/commit/18d8aad3affe84c762f2483c68bb551d97cf5689

**Comment by sylar6725** [comment]
It's not possible to set the Solution 1 in the installation script?
Document the problem in the FAQ is a good idea if someone is faced at this error. ( check permission and check if user is in "www-data" group, if not, add user in  "www-data" group with `sudo usermod -aG www-data USERNAME` or without sudo but in root)

**Comment by leiweibau** [comment]
I was already thinking yesterday about how to implement this. In the setup I need to detect which USERNAME is used, because it can differ from installation to installation. There are environment variables, but if I use "sudo" in setup, the USERNAME in that variable is "root". If you have a reliable idea, feel free to share it with me. I will think about this further though.

**Comment by leiweibau** [comment]
you can also use `~/pialert/back/pialert-cli set_permissions`
