### ISSUE TITLE
Network Page configuration 

### ISSUE THREAD

**Issue by jca001** [leiweibau/Pi.Alert#67]
I have a 5 port Router that I created on the Network Page. The Cable Modem (Internet) is connected to port 1 and I specified that in the Internet Device (Network Node) Router and (Connected to Port) 1. This populated Port 1 of the Routed. The other 4 Router Ports are connected to 4 (8 Port Switches) which I also created them on the Network Page. I configured each of the Device's (Network Node and Port) specifying the Router and Port they are connected to.

I cannot figure out how to configure the Router Device (Network Node and Port) to point to the 4 Switches so they get populated on the Switches on the Network Page. It only allows specifying 1 (Network Node and Port).

Another oddity: after selecting the (Network Node) from the list, the next time you look at the Device it just shows the Index Number, Not the Name.

I seems to me it would be better to be able to select the Port of the Router and/or Switch on the Network Page and get a list of Devices to select.

Or am I just missing something and not selecting something correctly?

**Comment by leiweibau** [comment]
The way I have designed the network page, you should proceed as follows.

Create the router as you have already done.
Create the 4 switches. If these switches are not smart switches or managed switches, then it doesn't work anymore, because I haven't implemented any "dummy devices" yet. But if they are switches with IPs, then you create these switches as already written.

The switches, you assign to the router, the clients to the switches.

The network page is as it is, certainly not equipped for every purpose.

> Another oddity: after selecting the (Network Node) from the list, the next time you look at the Device it just shows the Index Number, Not the Name.

That is correct. The name in the list is only to simplify the selection. Stored is the ID

**Comment by jca001** [comment]
Thanks for the quick reply.

All the Switches are Managed.

I have configured other devices (PCs, APs ...) and specified the Switch and Port they are connected to which populates the Port on the Switch on the Network Page. The 4 Router Ports are connected to Port 1 of each Switch, but there is no way to indicate this. Therefore the status of Port 1 on each Switch shows Offline and no other information. I guess I will just have to accept that is the way it works.

Another little problem I ran into is if the Network Page list is very long, then on the Device Page when selecting the (Network Node) the list goes off the screen. Therefore you cannot click on say index 6 and above. You have to go back to the Network Page and get the Index Number and then back to the Device Page and enter the Index Number. This may be a Browser problem, Chrome. I have not tried other browsers.

Thanks for all the work you have put into this Application.

**Comment by leiweibau** [comment]
With the last message, it was already night for me, which is why I was no longer properly concentrated. Now, however, I could recognize my thinking error. Unfortunately, I can not yet say when I will take care of it.

The problem from my point of view.
- You can assign one client or router to one switch port.
- You can assign several clients or routers to one switch port
- You can assign several switch ports to one client or router.
- But you can't map one client or router to multiple nodes. Unfortunately, I have not noticed this before, since I only use one large switch.

**Comment by jca001** [comment]
I understand.

To me it would be more natural to click on the Port Number on the Network Page and have a list of Devices to select from. The (Network Node and Port) on the Device could be updated for information, but not changeable on the Device Page.

I know this may require a good bit of changes and don't expect it to be done soon, but I hope you will give it some thought.

**Comment by leiweibau** [comment]
I totally agree with you there. Yes, that would be much easier. However, as the idea grew, I wanted to make as few changes to the DB as possible to keep compatibility with the original Pi.Alert as high as possible while creating as little duplicate data as possible. At the moment I would rather remove the network page or at least fix it a bit, than redo it completely. ;D 

Now I know that a few people are using my fork, which is why I am again cautious about making major changes to the DB. Finally I have to be able to make these changes afterwards with the update script without destroying the users data.
Maybe someone can be found to make a pull request.
